name: lint pr
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go lint-pr.yaml"

jobs:
  enforce-semantic-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
